import { title, subtitle} from "@/components/primitives";
import {BlueLink as Link} from "@/components/link" ;
export default function ContactPage() {
	return (
		<div className="max-w-4xl mx-auto text-justify">
			<div className = "my-4">
				<Link href = "/blog/">Return to all blog posts</Link>
			</div>
			<div className="my-4">
				<h1 className={title()}>4. PrepStar AI is live!</h1>
				<p className = "my-4">
					This will be a short update blog post. 
				</p>
				<p className = "my-4">
					Over the winter break, I was working on PrepStar AI hosted at (<Link href="https:www.prepstar.io">www.prepstar.io</Link>).
					PrepStar AI allows students to practice unlimited AP practice exams over at least fifteen AP subjects. The questions are 
					generated by large language models (LLMs), therefore students would be able to take an unique practice exam every single time.
					PrepStar AI offers one free practice exam for every student, and unlimited practices are available for $11.99 a month. 
				</p>
				<p className = "my-4">
					There are many tangible benefits to taking practice exams compared to just re-reading notes. Taking practice exams 
					allow students to discover knowledge gaps quickly and concentrate on areas needing improvement. Even if students are 
					sure about their knowledge in a certain chapter or unit, practice exams could allow them to discover places needing more
					improvement, such as a student confident in acids and bases could be less confident about working out buffer problems. 
				</p>
				<p className = "my-4">
					Practice exams are the most direct way for students to actively retrieve information. An analogy from nature to describe how 
					practice enhances information retrieval could be the process of a river carving a canyon. Initially, a river might start 
					as a small stream, flowing over a vast plain. As it flows, it gradually carves deeper into the path. 
					Over time, with continuous flow, the river carves a deep and distinct path through the landscape, creating a canyon.
				</p>
				<p className = "my-4">
					Similarly, when we first try to learn and retrieve new information, the neural pathways in our brain are like that small stream.
					 Each time we practice retrieving this information, It&apos;s like the water flowing over the same path again, reinforcing and 
					 deepening it. Just as the river&apos;s repeated flow carves a canyon, repeated practice of information retrieval strengthens and 
					 deepens the neural pathways in our brain, making the retrieval of that information more effortless and more efficient.
				</p>
			</div>
		</div>
	);
}
